# Generated by Django 6.0.2 on 2026-02-25 12:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('method', models.CharField(choices=[('card', 'Card'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('cod', 'Cash on Delivery'), ('netbanking', 'Net Banking')], max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('gateway', models.CharField(blank=True, max_length=50)),
                ('gateway_txn_id', models.CharField(blank=True, max_length=255)),
                ('gateway_response', models.JSONField(default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='orders.order')),
            ],
        ),
    ]
